export const CONSTANTS = {
  DATA_DIRECTORY: "app/data/tenants.json",
  A2C_ERROR_IDENTIFIER: [
    "MISSING_MANDATORY_ATTRIBUTE",
    "MISSING_CONFIGURATION",
    "AMOUNT_CURRENCY_MISMATCH",
    "NVALID_RESPONSE_FROM_PSP",
    "INCORRECT_CREDENTIALS",
    "INVALID_ATTRIBUTE",
    "INCONSISTENT_ATTRIBUTE",
    "INCONSISTENT_L2L3_CONFIGURATION",
    "CARD_AUTHORIZATION_MISMATCH",
    "INTERNAL_ERROR",
    "TIMEOUT",
  ],
  API_VERSION: 'V1'
};
